# Generated by Django 3.0.8 on 2020-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Subham', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
